Made it work with NodeJS 6.9.1 on arm7l (Orange Pi)
baltazorr/oled-i2c-bus pull request #2
Opened 2016-11-26 07:49 UTC by haraldkubota

Hi,

Took me some time to figure out why this was not working. Might be a too new NodeJS version (version 6 deprecated new Buffer(array) as an example, but mostly setTimeout(tick(callback),0) is notworking at all).

Tested on Orange Pi Zero on a 128x64 OLED via I²C. Works well now.
Thanks for creating this. I could not make oled-js-pi work (similar errors, probably related to NodeJS v6 too).

Harald

2016-11-28 14:26 UTC, baltazorr requested changes

2016-11-28 14:26 UTC, baltazorr commented on oled.js
> +  this.wire.i2cReadSync(this.ADDRESS, 1, Buffer.from(data));
Why did you change i2cReadrequest to i2cReadSync?

Please make this line compatible with older version of Node.js

2016-11-28 14:26 UTC, baltazorr commented on oled.js
> +  setTimeout(function(){tick(callback)}, 0);
This change is excessive

2016-11-28 14:26 UTC, baltazorr commented on oled.js
> +  this.buffer = Buffer.alloc((this.WIDTH * this.HEIGHT) / 8);
`Buffer.alloc` has appeared in version 6.0.0. It makes this lib incompatible with older version of Node.js. Can we make check if `Buffer.alloc` exists and use `new Buffer` if not exists?

2016-11-28 14:26 UTC, baltazorr commented on oled.js
> +  this.wire.i2cWrite(this.ADDRESS, 2, Buffer.from([control, val]), function(err) {
Please make this line compatible with older version of Node.js

2016-11-29 16:37 UTC, merged

2016-11-29 17:33 UTC, baltazorr commented
I have merged your pull request and made changes by my comments. Now it should work for all version of Node.js

Already updated in repository and available thru `npm install oled-i2c-bus`

2016-11-30 14:51 UTC, haraldkubota commented
Thanks a lot Bogdan! I was busy at work. Programming us for me a weekend
activity only. Your comments did make sense and I planned to fix them, but
if you already did, that's even better. And faster.

The change to sync read was for debugging purpose and was not expected to
stay. Was not even supposed to be in a commit.
I'll better check my upstream patches next time.

Thanks,
Harald

On Nov 30, 2016 02:33, "Bogdan Symchych" <notifications@github.com> wrote:

> I have merged your pull request and made changes by my comments. Now it
> should work for all version of Node.js
>
> Already updated in repository and available thru npm install oled-i2c-bus
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/baltazorr/oled-i2c-bus/pull/2#issuecomment-263639915>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJDl8tuA1DOjMaDWsgcK90fY7mFqCQd9ks5rDGHigaJpZM4K81bx>
> .
>